hydra:
  job:
    name: "two-models_${expt.num_passes}-passes_optuna-best-lambdas"

lambdas: [1, 41.27465239183713, 13.383203871890492, 0.7817070082023581, 1.369513212383596]
# [nll, penalty, consistency, repr_consistency, alignment]

error_decay_factor: 1.0

main_data: newsemp
is_two_models: True

lbl_split: 1
num_passes: 4

do_tune: False
do_augment: True

overwrite_parent_dir: null
