hydra:
  job:
    name: "two-models_${expt.num_passes}-passes_optuna-best-lambdas-updated-rescaling"

lambdas: [1, 10.373612129895633, 4.964834667475371, 14.942130457174258, 2.995967273728681]
# [nll, penalty, consistency, repr_consistency, alignment]

error_decay_factor: 1.0

main_data: empstories
is_two_models: True

lbl_split: 1
num_passes: 4

do_tune: False
do_augment: True

overwrite_parent_dir: null
