hydra:
  job:
    name: "label-noise-0.2"

approach: cross-basic
is_two_models: False

lambdas: [null, null, 0]
# [NA, NA, alignment]

do_augment: False

sanitise_labels: True # sanitise all train, val, test data
delta: 2.0 # keeping it 1-label shift, which is fixed to 3.0 in preprocessing
# the reason is low delta will ensure better sanitised labels, as samples
# differed by delta is being removed.
add_noise_train: True
add_noise_test: False

#### Resume training
overwrite_parent_dir: null
