hydra:
  job:
    name: "single-model_${expt.num_passes}-passes-label-noise-0.2"

# FIXED
is_two_models: False

# Can change
num_passes: 4

lambdas: [1, 27.763313657833034, 14.919400077248078]
# [nll, penalty, alignment]

do_tune: False
do_augment: False # can't be true as loading augmented data cannot sanitise and add noise

sanitise_labels: True # sanitise all train, val, test data
delta: 2.0 # keeping it 1-label shift, which is fixed to 3.0 in preprocessing
# the reason is low delta will ensure better sanitised labels, as samples
# differed by delta is being removed.
add_noise_train: True
add_noise_test: False

overwrite_parent_dir: null
