hydra:
  job:
    # name: "single-cross-prob-lambda1-${expt.lambda_1}-decay-${expt.error_decay_factor}-lambda2-${expt.lambda_2}"
    name: "single-cross-prob-tune-${n_trials}"

approach: cross-prob
is_two_models: False

lambda_1: 1.0 # penalty
error_decay_factor: 1.0 # if lambda_1 != 0
lambda_2: 0.0 # alignment

overwrite_parent_dir: outputs/2025-06-05/00-29-41_single-cross-prob-tune-50
