hydra:
  job:
    name: "single-model_lambdas-${expt.lambdas}_${expt.num_passes}-passes"

is_two_models: False
num_passes: 4

lambdas: [1, 0, 1]
# [nll, penalty, alignment]

overwrite_parent_dir: null
