hydra:
  job:
    name: "ssl-${expt.lbl_split}-lambda1-${expt.lambda_1}-lambda2-${expt.lambda_2}-variational-ensemble"

lambda_1: 1
lambda_2: 1 # SSL - consistency loss
lambda_3: 1 # repr consistency loss
