hydra:
  job:
    name: "" # doesn't matter as we save it in the parent dir

approach: cross-basic
is_ssl: False

do_train: False
do_test: True
overwrite_parent_dir: outputs/2025-07-20/14-49-10_newsemp_cross-basic_split-0.1_lambda2-0
