hydra:
  job:
    name: "" # doesn't matter as we save it in the parent dir

do_train: False
do_test: True
overwrite_parent_dir: outputs/2025-07-20/15-14-43_newsemp_cross-prob_split-0.1_lambda0-1_lambda1-0_lambda2-0_lambda3-0
