hydra:
  job:
    name: "single-model_${expt.num_passes}-passes"

# FIXED
is_two_models: False

# Can change
num_passes: 4

lambdas: [null, null, null] # being tuned / set in optuna objective
# [nll, penalty, alignment]

do_tune: True
n_trials: 10

overwrite_parent_dir: outputs/2025-07-28/01-58-09_newsemp_cross-prob_lambdas-[None, None, None]_tune-True_single-model_4-passes
