# these are just to retrieve the correct file names for newsemp dataset.
# actual train and val data depends on main_data
train_data: [2024, 2022]
val_data: 2024 # test would be same as val_data as in in-sample setting

debug: False

# num_epochs: 20
max_steps: 6000 # 4000 originally
val_check_interval: 200 # num steps (if int) or portion of epoch (if float)
lr: 3.0e-5
train_bsz: 16
eval_bsz: 16
parent_log_dir: ./log

n_trials: 50

# seeds: [0, 42, 100, 999, 1234]
seeds: [0]

main_data: newsemp # options: newsemp, empstories

# Only keep samples if the difference between 'empathy' and 'llm_empathy' < delta
# If delta is null (i.e, None), then we don't filter any samples
delta: null

error_decay_factor: 0.0
lambda_1: 1 # penalty weight for non-SSL and unlabel_weight for SSL
lambda_2: 1 # only for SSL
lambda_3: 1 # only for SSL

approach: cross-prob # options: siamese, cross-basic, bi-prob, cross-prob
expt_name_postfix: null
do_tune: True
do_train: True

is_ssl: True 

# Note: It's only the parent diretory like log/yyyymmdd_hhmmss_xx but nothing after that
overwrite_parent_dir: null 

# all files list that we can use for training / validation / testing
2024:
    train: data/NewsEmp2024/trac3_EMP_train.csv
    train_llama: data/NewsEmp2024/trac3_EMP_train_llama.tsv
    train_gpt: data/NewsEmp2024/trac3_EMP_train_gpt.tsv
    val: data/NewsEmp2024/trac3_EMP_dev.csv
    val_llama: data/NewsEmp2024/trac3_EMP_dev_llama.tsv
    val_gpt: data/NewsEmp2024/trac3_EMP_train_gpt.tsv
    test: data/NewsEmp2024/test_data_with_labels/goldstandard_EMP.csv
    test_llama: data/NewsEmp2024/test_data_with_labels/goldstandard_EMP_llama.tsv
2023:
    train: data/NewsEmp2023/WASSA23_essay_level_with_labels_train.tsv
    train_llama: data/NewsEmp2023/WASSA23_essay_level_with_labels_train_llama.tsv
    val: data/NewsEmp2023/WASSA23_essay_level_dev.tsv 
    val_llama: data/NewsEmp2023/WASSA23_essay_level_dev_llama.tsv
    test: data/NewsEmp2023/WASSA23_essay_level_test.tsv
2022:
    train: data/NewsEmp2022/messages_train_ready_for_WS.tsv
    train_llama: data/NewsEmp2022/messages_train_ready_for_WS_llama.tsv
    val: data/NewsEmp2022/messages_dev_features_ready_for_WS_2022.tsv
    val_llama: data/NewsEmp2022/messages_dev_features_ready_for_WS_2022_llama.tsv
    test: data/NewsEmp2022/messages_test_features_ready_for_WS_2022.tsv
